--CRIAÇÃO DA TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO (
	id_funcionario SERIAL NOT NULL,
	nome varchar(150) NOT NULL,
	cargo varchar(45) NOT NULL,
	email varchar(150) NOT NULL UNIQUE,
	ADD CONSTRAINT PK_IDFUNC PRIMARY KEY (id_funcionario),
	ADD CONSTRAINT CK_CARGO CHECK (cargo IN  ('Programador', 'Técnico', 'Gestão'))
);


--CRIAÇÃO DA TABELA CLIENTE
CREATE TABLE CLIENTE (
	id_cliente SERIAL NOT NULL,
	telefone VARCHAR(45),
	nome VARCHAR(150) NOT NULL,
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(id_cliente)
);

--CRIAÇÃO DA TABELA DE ENDEREÇOS
CREATE TABLE ENDERECO (
	id_cliente INTEGER NOT NULL,
	rua VARCHAR(70) NOT NULL,
	numero VARCHAR(10) NOT NULL SET DEFAULT 'S/N',
	complemento VARCHAR(45),
	bairro VARCHAR(45) NOT NULL,
	estado CHAR(2) NOT NULL SET DEFAULT 'PB',
	cidade VARCHAR(45) NOT NULL SET DEFAULT 'João Pessoa',
	ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (id_cliente),
	ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(id_cliente) REFERENCES CLIENTE
);


--CRIANDO A TABELA DE ATENDIMENTOS
CREATE TABLE ATENDIMENTO (
	id_atendimento SERIAL NOT NULL,
	url_relatorio VARCHAR(300) NOT NULL,
	data_atend DATE NOT NULL,
	id_func INTEGER NOT NULL,
	id_cli INTEGER NOT NULL,
	ADD CONSTRAINT PK_ATEND PRIMARY KEY(id_atendimento),
	ADD CONSTRAINT FK_FUNC FOREIGN KEY (id_func) REFERENCES FUNCIONARIO,
	ADD CONSTRAINT FK_CLI FOREIGN KEY (id_cli) REFERENCES CLIENTE
);


--CRIAÇÃO DA TABELA DE SERVIÇOS
CREATE TABLE SERVICO(
	id_servico SERIAL NOT NULL,
	tipo VARCHAR(45) NOT NULL,
	ADD CONSTRAINT PK_SERVICO PRIMARY KEY(id_servico)
);

--CRIAÇÃO DA TABELA ATENDIMENTO-SERVIÇO
CREATE TABLE ATENDSERVICO(
	id_servico INTEGER NOT NULL,
	id_atendimento INTEGER NOT NULL,
	ADD CONSTRAINT FK_ATEND FOREIGN KEY(id_atendimento) REFERENCES ATENDIMENTOS,
	ADD CONSTRAINT FK_SERVICO FOREIGN KEY(id_servico) REFERENCES CLIENTE,
	ADD CONSTRAINT PK_ATENDSERV PRIMARY KEY(id_atendimento, id_servico)
);

SELECT * FROM FUNCIONARIO;
SELECT * FROM CLIENTE;
SELECT * FROM ENDERECO;
SELECT * FROM ATENDIMENTO;
SELECT * FROM SERVICO;
SELECT * FROM ATENDSERVICO;