--CRIAÇÃO DA TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO (
	id_funcionario SERIAL NOT NULL,
	nome varchar(150) NOT NULL,
	cargo varchar(45) NOT NULL,
	email varchar(150) NOT NULL UNIQUE
);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT PK_IDFUNC PRIMARY KEY (id_funcionario);

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT CARGO_CHECK CHECK (cargo IN  ('Programador', 'Técnico', 'Gestão'));

SELECT * FROM FUNCIONARIO;

--CRIAÇÃO DA TABELA CLIENTE
CREATE TABLE CLIENTE (
	id_cliente SERIAL NOT NULL,
	telefone VARCHAR(45),
	nome VARCHAR(150) NOT NULL 
);

ALTER TABLE CLIENTE 
ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(id_cliente);

SELECT * FROM CLIENTE;

--CRIAÇÃO DA TABELA DE ENDEREÇOS
CREATE TABLE ENDERECO(
	id_cliente INTEGER NOT NULL,
	rua VARCHAR(70) NOT NULL,
	numero VARCHAR(10) NOT NULL,
	complemento VARCHAR(45),
	bairro VARCHAR(45) NOT NULL,
	estado CHAR(2) NOT NULL,
	cidade VARCHAR(45) NOT NULL
);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_CLIENTE FOREIGN KEY(id_cliente)
REFERENCES CLIENTE;

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (id_cliente);

--SETANDO OS VALORES DEFAULT PARA A TABELA ENDEREÇO
ALTER TABLE ENDERECO
ALTER COLUMN numero SET DEFAULT 'S/N';

ALTER TABLE ENDERECO
ALTER COLUMN estado SET DEFAULT 'PB';

ALTER TABLE ENDERECO
ALTER COLUMN cidade SET DEFAULT 'João Pessoa';

SELECT * FROM ENDERECO;

--CRIANDO A TABELA DE ATENDIMENTOS
CREATE TABLE ATENDIMENTOS(
	id_atendimento SERIAL NOT NULL,
	url_relatorio VARCHAR(300) NOT NULL,
	data_atend DATE NOT NULL,
	id_func INTEGER NOT NULL,
	id_cli INTEGER NOT NULL
);

ALTER TABLE ATENDIMENTOS
ADD CONSTRAINT PK_ATEND PRIMARY KEY(id_atendimento);

ALTER TABLE ATENDIMENTOS
ADD CONSTRAINT FK_FUNC FOREIGN KEY (id_func)
REFERENCES FUNCIONARIO;

ALTER TABLE ATENDIMENTOS
ADD CONSTRAINT FK_CLI FOREIGN KEY (id_cli)
REFERENCES CLIENTE;

SELECT * FROM ATENDIMENTOS;

--CRIAÇÃO DA TABELA SERVIÇOS
CREATE TABLE SERVICOS(
	id_servico SERIAL NOT NULL,
	tipo VARCHAR(45) NOT NULL
);

ALTER TABLE SERVICOS
ADD CONSTRAINT PK_SERVICO PRIMARY KEY(id_servico);

--CRIAÇÃO DA TABELA ATENDIMENTO-SERVIÇO
CREATE TABLE ATENDSERVICO(
	id_servico INTEGER NOT NULL,
	id_atendimento INTEGER NOT NULL
);

ALTER TABLE ATENDSERVICO
ADD CONSTRAINT FK_ATEND FOREIGN KEY(id_atendimento)
REFERENCES ATENDIMENTOS;

ALTER TABLE ATENDSERVICO
ADD CONSTRAINT FK_SERVICO FOREIGN KEY(id_servico)
REFERENCES CLIENTE;

ALTER TABLE ATENDSERVICO
ADD CONSTRAINT PK_ATENDSERV PRIMARY KEY(id_atendimento, id_servico);

SELECT * FROM ATENDSERVICO;
